onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /lab_3_tb_top_ex6/clk
add wave -noupdate /lab_3_tb_top_ex6/rst
add wave -noupdate /lab_3_tb_top_ex6/ena
add wave -noupdate /lab_3_tb_top_ex6/TBactive
add wave -noupdate /lab_3_tb_top_ex6/ITCM_tb_wr
add wave -noupdate /lab_3_tb_top_ex6/ITCM_tb_in
add wave -noupdate /lab_3_tb_top_ex6/ITCM_tb_addr_in
add wave -noupdate /lab_3_tb_top_ex6/DTCM_tb_wr
add wave -noupdate /lab_3_tb_top_ex6/DTCM_tb_in
add wave -noupdate /lab_3_tb_top_ex6/DTCM_tb_out
add wave -noupdate /lab_3_tb_top_ex6/DTCM_tb_addr_in
add wave -noupdate /lab_3_tb_top_ex6/DTCM_tb_addr_out
add wave -noupdate /lab_3_tb_top_ex6/done
add wave -noupdate /lab_3_tb_top_ex6/sim_done
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/clk
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/rst
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/ena
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/mov_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/done_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/and_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/or_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/xor_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/jnc_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/jc_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/jmp_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/sub_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/add_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/ld_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/st_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/Cflag
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/Zflag
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/Nflag
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/DTCM_wr
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/Cin
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/Cout
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/DTCM_addr_in
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/DTCM_out
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/ALUFN
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/Ain
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/RFin
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/RFout
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/RFaddr_rd
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/RFaddr_wr
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/IRin
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/PCin
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/PCsel
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/Imm1_in
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/Imm2_in
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/done
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/state_reg
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/next_state
add wave -noupdate /lab_3_tb_top_ex6/DUT/CU/rtype_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/clk
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/rst
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/DTCM_wr
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/Cin
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/Cout
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/DTCM_addr_in
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/DTCM_out
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/ALUFN
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/Ain
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/RFin
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/RFout
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/RFaddr_rd
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/RFaddr_wr
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/IRin
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/PCin
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/PCsel
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/Imm1_in
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/Imm2_in
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/mov_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/done_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/and_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/or_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/xor_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/jnc_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/jc_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/jmp_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/sub_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/add_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/ld_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/st_s
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/Cflag
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/Zflag
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/Nflag
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/TBactive
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/ITCM_tb_wr
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/ITCM_tb_in
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/ITCM_tb_addr_in
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/DTCM_tb_wr
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/DTCM_tb_in
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/DTCM_tb_out
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/DTCM_tb_addr_in
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/DTCM_tb_addr_out
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/BUS_wire
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/IR_reg
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/PC_reg
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/REG_A
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/REG_C
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/DTCM_addr_reg
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/ALU_result
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/ALU_C
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/ALU_Z
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/ALU_N
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/flag_C
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/flag_Z
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/flag_N
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/is_rtype
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/PC_plus1
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/PC_next
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/Imm1_sext
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/Imm2_sext
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/RF_rdata
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/RF_read_addr
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/RF_write_addr
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/ITCM_data
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/DTCM_data
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/ITCM_rd_addr
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/DTCM_rd_addr
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/DTCM_wr_addr
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/DTCM_wr_data
add wave -noupdate /lab_3_tb_top_ex6/DUT/DP/DTCM_wr_en
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {15919050 ps} {15920050 ps}
